name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        sudo apt install -y libpcap0.8-dev  
        go get -v 
      working-directory: "./src"

    - name: Build
      run: go build -v .
      working-directory: "./src"

    - name: Test
      run: go test -v .
      working-directory: "./src"

    - name: generate sample config file 
      run: ./dnsmonster --writeConfig=../config-sample.ini
      working-directory: "./src"

    - name: update README command line options
      run: |
        START="$(($(grep -n "start of command line options" README.md | cut -f1 -d:)+2))"
        END="$(($(grep -n "end of command line options" README.md | cut -f1 -d:)-2))"
        USAGE=$(cat <<-END
        $(COLUMNS=120 ./src/dnsmonster --help | sed -r 1d)
        END
        )
        awk -v var="$USAGE" 'NR=='$START'{print var} NR<'$START' || NR>'$END README.md > README.tmp
        mv README.tmp README.md
      working-directory: "."

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Ali Mosajjal
        author_email: mosajjal@gmail.com
        message: "auto update sample ini"
        add: "config-sample.ini README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
