name: Publish binaries on Release
on: 
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        docker build -t myrepo:latest -f Dockerfile-release .
        id=$(docker create myrepo:latest)
        docker cp $id:/tmp/dnsmonster-linux-amd64.bin /tmp/dnsmonster-linux-amd64.bin
        docker cp $id:/tmp/dnsmonster-windows-amd64.exe /tmp/dnsmonster-windows-amd64.exe
        strip --strip-all /tmp/dnsmonster-linux-amd64.bin
        tar czf /tmp/dnsmonster-linux-amd64.bin.tar.gz -C /tmp/ dnsmonster-linux-amd64.bin

    - name: build .deb file in /tmp/dnsmonster*.deb
      run: |
        # get version from latest git tag
        export VER=$(git describe --tags --abbrev=0|sed -e 's/^v//')
        # create a directory to build the debian package in
        DIR="/tmp/dnsmonster_$VER-1_amd64"
        # remove possible previous build temp files
        rm -rf $DIR
        mkdir -p $DIR/sbin $DIR/usr/share/man/man7 $DIR/DEBIAN $DIR/etc/bash_completion.d/ $DIR/usr/share/fish/vendor_completions.d
        docker build -t dnsmonster-build:temp --no-cache --pull -f Dockerfile-release .
        ID=$(docker create dnsmonster-build:temp)
        docker cp $ID:/tmp/dnsmonster-linux-amd64.bin $DIR/sbin/dnsmonster
        # remove temp container and image
        docker rm -f $ID
        docker rmi  -f dnsmonster-build:temp
        # generate manfile and completion files into appropiate locations
        $DIR/sbin/dnsmonster --manPage > $DIR/usr/share/man/man7/dnsmonster.7
        $DIR/sbin/dnsmonster --bashCompletion > $DIR/etc/bash_completion.d/dnsmonster.bash
        $DIR/sbin/dnsmonster --fishCompletion > $DIR/usr/share/fish/vendor_completions.d/dnsmonster.fish
        cat << EOF > $DIR/DEBIAN/control
        Package: dnsmonster
        Version: $VER
        Architecture: amd64
        Maintainer: Ali Mosajjal <hi@n0p.me>
        Description: Passive DNS monitoring framework.
        EOF
        dpkg-deb --build --root-owner-group $DIR

    - name: Upload Linux binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/dnsmonster-linux-amd64.bin.tar.gz
        asset_name: dnsmonster-musl-static-stripped-amd64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""

    - name: Upload windows binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/dnsmonster-windows-amd64.exe
        asset_name: dnsmonster-windows-amd64.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: ""

    - uses: actions/upload-artifact@v2
      with:
        name: dnsmonster-latest.deb
        path: /tmp/dnsmonster*.deb