name: Sync Readme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

steps:
- uses: actions/checkout@main

- uses: meeDamian/sync-readme@v1.0.6
  with:
    pass: ${{ secrets.DOCKER_PASS }}
    description: true
  